import time
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://omayo.blogspot.com/")
driver.execute_script("history.go(0)")
time.sleep(5)
driver.execute_script("window.scrollBy(0,500)")
time.sleep(5)
driver.execute_script("history.go(0)")
time.sleep(5)
driver.execute_script("window.scrollBy(0,document.body.scrollHeight)")
time.sleep(5)
driver.execute_script("window.scrollBy(0,-500)")
time.sleep(5)
blogger = driver.find_element(By.XPATH, value="//a[text()='Blogger']")
driver.execute_script("arguments[0].scrollIntoView(true);", blogger)
page_text = str(driver.execute_script("return document.documentElement.innerText"))
print(page_text)
driver.quit()